#!/usr/bin/env python3
"""Write the Step 6 Phase 5 report artifacts.

A repository-tracked generator, so the notes are reproducible. Re-running it
must produce byte-identical files, and `--check` fails if the committed files
have drifted.

Artifacts written under `notes/`:

  installed-hardware-interfaces.md    vector table, register map, dependency map
  installed-hardware-interfaces.json  the same, complete and machine-readable

No device access. Examples:
    python3 tool/report_phase5.py
    python3 tool/report_phase5.py --check
"""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

import extract_installed_records as ex
import falchion_image as fi
import map_hardware_interfaces as mh

ROOT = Path(__file__).resolve().parent.parent
NOTES = ROOT / "notes"

ARTIFACTS = ("installed-hardware-interfaces.md",
             "installed-hardware-interfaces.json")


def markdown(hardware):
    payload = mh.to_dict(hardware)
    lines = [
        "# Installed 1.59 hardware and runtime interface map",
        "",
        "Generated by `tool/report_phase5.py` from",
        "`tool/map_hardware_interfaces.py`, which combines the vector table",
        "parsed out of Candidate A's own bytes,",
        "`ghidra/scripts/FalchionPeripheralMap.java` (every load and store whose",
        "base register Ghidra's constant propagation resolves), and the call",
        "graph from `ghidra/scripts/FalchionFunctionInventory.java`.",
        "",
        "Offline and read-only; no device was accessed and no dump was modified.",
        "",
        "## Two rules this map keeps",
        "",
        "**Observed behaviour is separated from address-space identity.** There",
        "is no public SNC73270 reference manual in this repository, so an address",
        "space with no positive evidence behind it is classified `unknown` — this",
        "map does not call something a vendor peripheral merely because it is not",
        "anything else. The only names here come from the ARMv7-M architecture,",
        "which applies to any Cortex-M3. Nothing in this map supports a claim",
        "about USB, key scanning, Hall-effect sensing, nonvolatile storage or RGB",
        "hardware.",
        "",
        "**Classification is per address, not per block.** The application image",
        "and the RAM above it share a 1 MiB block, and the proven runtime range",
        "ends at `0x18036168` rather than at a block boundary, so labelling a",
        "whole block would manufacture false categories. Blocks whose addresses",
        "have more than one kind are reported as `mixed`.",
        "",
        "**Reachability is computed, not assumed.** Each function's context comes",
        "from a breadth-first walk of the call graph out of roots that are",
        "themselves evidence: the vector-table entries, plus the two entry-image",
        "words that point into the application's code. A function no root reaches",
        "is reported as unreached.",
        "",
        "## Status of this phase",
        "",
        f"**{payload['phase_status']['state']}.** "
        + payload["phase_status"]["reason"],
        "",
        "## Vector table",
        "",
        f"- span: logical `0x{payload['vector_table_span']['lo']:x}.."
        f"0x{payload['vector_table_span']['hi']:x}` inside the entry image",
        f"- slots: {len(payload['vector_table'])} = 16 core + "
        f"{len(payload['vector_table']) - len(mh.CORE_VECTORS)} external",
        f"- fill value: `0x{payload['fill_value']:08x}`, the value repeated "
        "across unused slots",
        "",
        "An ARMv7-M vector table has **no terminator**, so nothing here looks",
        "for one. The table runs from the image base to the first code address",
        "and every word in between is a slot. The repeated fill value marks a",
        "slot *unused*; it does not end the table, and a live slot can and does",
        "follow it — `IRQ63` at offset `0x13c` holds `0x00000ad1`, a Thumb",
        "pointer to the callerless function at `0x00000ad0`.",
        "",
        "| slot | name | value | kind | target |",
        "|---|---|---|---|---|",
    ]
    for slot in payload["vector_table"]:
        if slot["kind"] in ("zero", "fill"):
            continue
        target = ("—" if slot["target_function"] is None
                  else f"{slot['target_program']} image "
                       f"`0x{slot['target_function']:08x}`")
        lines.append(f"| {slot['index']} | {slot['name']} | "
                     f"`0x{slot['value']:08x}` | {slot['kind']} | {target} |")
    zeros = sum(1 for slot in payload["vector_table"] if slot["kind"] == "zero")
    fills = sum(1 for slot in payload["vector_table"] if slot["kind"] == "fill")
    lines += [
        "",
        f"{fills} slots hold the fill value and {zeros} are zero; they are "
        "omitted from the table above.",
        "",
    ]
    lines += [
        "## Cross-image entry points",
        "",
        f"{len(payload['code_entries'])} entry-image words point into the "
        "application's materialised code range with the Thumb bit set. Seven of",
        "them are the interrupt vectors above; the remaining two are how the",
        "entry image transfers control after the scatter load:",
        "",
    ]
    for pointer in payload["code_entries"]:
        if pointer["in_vector_table"]:
            continue
        lines.append(f"- entry image `0x{pointer['entry_offset']:04x}` -> "
                     f"`0x{pointer['value']:08x}`")
    lines += [
        "",
        f"A further {len(payload['data_pointers'])} entry-image words point into "
        "application RAM outside the code range. Those are shared variables, not",
        "entry points, and are listed in the JSON.",
        "",
        "## What the values say",
        "",
        "Each statement below is a predicate the tool evaluates over the",
        "assembled map, so it is checked rather than asserted, and each carries",
        "its own basis and confidence.",
        "",
    ]
    for item in payload["notable_observations"]:
        lines += [
            f"### {item['statement']}",
            "",
            f"- basis: {item['basis']}",
            f"- confidence: {item['confidence']}",
            "",
        ]

    lines += ["## Register map", ""]
    for program in payload["programs"]:
        lines += [
            f"### {program['name']}",
            "",
            f"- slice `{program['slice']}` at base "
            f"`0x{program['base']:08x}`",
            f"- {program['functions']} functions, "
            f"{program['reached_functions']} reached from a vector root, "
            f"{len(program['unreached_functions'])} unreached",
            f"- {program['accesses']} accesses with a resolved base; "
            f"{sum(program['unresolved_accesses'].values())} unresolved",
            "",
            "Unresolved reasons: "
            + ", ".join(f"`{reason}` {count}" for reason, count
                        in program["unresolved_accesses"].items()) + ".",
            "",
        ]
        for block in program["blocks"]:
            lines += [
                f"#### `0x{block['base']:08x}` — {block['kind']}, "
                f"{len(block['registers'])} registers, "
                f"{block['accesses']} accesses",
                "",
                block["description"],
                "",
                "Contexts: " + ", ".join(block["contexts"]) + ".",
                "",
            ]
            # RAM, own-image and artifact addresses are not peripheral claims,
            # so they are counted but not tabulated. A mixed block still shows
            # the addresses that are *not* those kinds, which is how the one
            # access past the proven runtime end stays visible.
            skip = ("runtime-ram", "program", "artifact")
            if block["kind"] in skip:
                continue
            interesting = [item for item in block["registers"]
                           if item["kind"] not in skip]
            if not interesting:
                continue
            if len(interesting) != len(block["registers"]):
                lines += [
                    f"{len(block['registers']) - len(interesting)} of these "
                    "addresses are RAM, own-image or propagation artifacts and "
                    "are omitted here; the complete list is in the JSON.",
                    "",
                ]
            lines += ["| address | kind | ARM name | widths | reads | "
                      "writes | stored values | reset-reachable writes | contexts | "
                      "confidence |",
                      "|---|---|---|---|---|---|---|---|---|---|"]
            for item in interesting:
                stored = (", ".join(f"`0x{value:x}`"
                                    for value in item["stored_values"])
                          or "—")
                init = (", ".join(f"`0x{value:x}`"
                                  for value in item["reset_reachable_write_values"])
                        or "—")
                lines.append(
                    f"| `0x{item['address']:08x}` | {item['kind']} | "
                    f"{item['arm_name'] or '—'} | "
                    f"{', '.join(str(width) for width in item['widths'])} | "
                    f"{len(item['read_sites'])} | {len(item['write_sites'])} | "
                    f"{stored} | {init} | {', '.join(item['contexts'])} | "
                    f"{item['confidence']} |")
            lines += ["",
                      "`reset-reachable writes` are writes from a function "
                      "the call graph reaches from the Reset vector. That is "
                      "reachability, not proof that the function runs during "
                      "initialisation, so the column is named for what it "
                      "measures. An aggregate of every value ever stored is a "
                      "different thing again, which is why the two are separate.",
                      ""]

    lines += [
        "## Dependency map",
        "",
        "The exit gate for this phase: which original services a minimal custom",
        "firmware must replace, which it may omit, and which are unknown. Each",
        "verdict is a stated rule applied to the evidence above, not an opinion.",
        "",
        "| verdict | block | kind | program | registers | accesses |",
        "|---|---|---|---|---|---|",
    ]
    for row in payload["dependency_map"]:
        lines.append(f"| {row['verdict']} | `0x{row['block']:08x}` | "
                     f"{row['kind']} | {row['program']} | {row['registers']} | "
                     f"{row['accesses']} |")
    lines += ["", "### Why each verdict", ""]
    seen = set()
    for row in payload["dependency_map"]:
        if row["verdict"] in seen:
            continue
        seen.add(row["verdict"])
        lines.append(f"- **{row['verdict']}**: {row['reason']}")
    lines += [
        "",
        "The exit gate asks which original **services** a minimal replacement",
        "must provide. This map cannot answer that, because it classifies",
        "*address spaces* and no vendor address space here is identified. What",
        "it does establish: a replacement must program the ARMv7-M core blocks",
        "itself; the address spaces the reset path programs before any service",
        "exists (`0x40000000`, `0x08000000`, `0x10000000`) must be reproduced or",
        "shown unnecessary; `0x45000000` and `0x40100000` are **blocked** rather",
        "than conditionally permitted, since nothing identifies what they do;",
        "and reading the mapped flash window is storage rather than a platform",
        "service. Treat the gate as partly met and partly blocked on a SNC73270",
        "reference manual.",
        "",
        "## Coverage of the planned analysis areas",
        "",
        "| area | state | reason |",
        "|---|---|---|",
    ]
    for item in payload["coverage"]:
        lines.append(f"| {item['area']} | {item['state']} | {item['reason']} |")

    if payload["contradictions"]:
        lines += ["", "## Contradictions recorded, not resolved", ""]
        for line in payload["contradictions"]:
            lines += [f"- {line}", ""]

    lines += [
        "",
        "## Limitations",
        "",
        "- Vendor MMIO blocks are described by observed accesses only. This map",
        "  names no vendor peripheral.",
        "- An access appears only when constant propagation resolved its base",
        "  register. Accesses through a pointer held in a parameter or a",
        "  structure are counted as unresolved, so the register list is a lower",
        "  bound rather than a complete set.",
        "- Reachability follows Ghidra's call graph, which does not follow calls",
        "  through function-pointer tables. The application image reports many",
        "  unreached functions for that reason; its task entry points are",
        "  dispatched through tables (logs 48, 49, 65), not called directly.",
        "- Handler functions exist in the analysis only because",
        "  `FalchionSeedVectors.java` created them from the vector table. A raw",
        "  binary import gives Ghidra no reason to disassemble a handler that",
        "  nothing calls.",
        "",
        "## Still unresolved",
        "",
    ]
    for line in fi.UNRESOLVED:
        lines.append(f"- {line}")
    lines += ["", "## Raw tool output", "", "```text"]
    lines += mh.report_lines(hardware, max_registers=0)
    lines += ["```", ""]
    return "\n".join(lines)


def render():
    hardware = mh.build_map()
    return {
        "installed-hardware-interfaces.md": markdown(hardware),
        "installed-hardware-interfaces.json": json.dumps(
            mh.to_dict(hardware), indent=2, sort_keys=True) + "\n",
    }


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the artifacts on disk match a fresh render")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    try:
        rendered = render()
    except (OSError, ValueError, KeyError, fi.ImageFormatError,
            ex.ExtractError) as exc:
        print(f"RESULT reports_written=0 error={exc}")
        return 1
    stale = []
    for name, text in rendered.items():
        path = NOTES / name
        if args.check:
            current = path.read_text() if path.exists() else None
            if current != text:
                stale.append(name)
            continue
        path.write_text(text)
        print(f"WROTE notes/{name} ({len(text)} bytes)")
    if args.check:
        for name in ARTIFACTS:
            print(f"  {'STALE' if name in stale else 'CURRENT'} notes/{name}")
        print(f"RESULT reports_current={not stale} stale={len(stale)}")
        return 1 if stale else 0
    print(f"RESULT reports_written={len(rendered)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
