#!/usr/bin/env python3
"""Write the Step 6 Phase 3 report artifacts.

One repository-tracked generator, so the notes are reproducible rather than the
output of a throwaway script. Re-running it must produce byte-identical files.

Artifacts written under `notes/`:

  installed-record-load-map.md        record, load and scatter map
  installed-record-load-map.json      the same, machine-readable
  vendor-to-installed-functions.md    the *complete* correspondence, every pairing
  vendor-to-installed-functions-app-a.json
  vendor-to-installed-functions-app-b.json

The two JSON correspondence files are the preserved complete mapping; the
Markdown carries every pairing as a table as well, so nothing important lives
only in an ignored directory.

Inputs are the preserved evidence binaries plus the function inventories under
`ghidra/inventories/`, which are produced by
`ghidra/scripts/FalchionFunctionInventory.java`. See `ghidra/README.md` for the
headless commands.

No device access. Example:
    python3 tool/report_phase3.py
    python3 tool/report_phase3.py --check
"""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

import extract_installed_records as ex
import falchion_image as fi
import match_functions as mf

ROOT = Path(__file__).resolve().parent.parent
NOTES = ROOT / "notes"
IMPORTS = ROOT / "ghidra/imports"
INVENTORIES = ROOT / "ghidra/inventories"

VENDOR = ROOT / "dumps/vendor/M605_V01_00_58.bin"
INSTALLED = (ROOT / "dumps/device"
             / "ROG_Falchion_Ace_HFX_installed_bcdDevice_1.59_app_0x10000_0x7bfff.bin")

# Raw byte-position differences from log 96, for the aligned-versus-raw contrast.
RAW_DIFFERING_BYTES = {"a": 131, "b": 101112}
PAIRS = (("a", 0x0, 0x11000), ("b", 0x18000000, 0x21000))


def slice_for(extraction, import_base):
    """The extracted slice whose import base is the one asked for."""
    found = [item for item in extraction.slices
             if item.import_base == import_base]
    if len(found) != 1:
        raise SystemExit(
            f"expected exactly one slice with import base {import_base!r}, "
            f"found {len(found)}")
    return found[0]


def load_reports():
    vendor = ex.extract(fi.ImageView(VENDOR.read_bytes(), 0))
    installed = ex.extract(fi.ImageView(INSTALLED.read_bytes(), 0x10000))
    reports = {}
    for tag, base, flash_base in PAIRS:
        import_base = 0x0 if tag == "a" else 0x18000000
        vendor_slice = slice_for(vendor, import_base)
        installed_slice = slice_for(installed, import_base)
        reports[tag] = mf.build_report(
            f"app_{tag}",
            (INVENTORIES / f"vendor_{tag}.txt").read_text(),
            (INVENTORIES / f"installed_{tag}.txt").read_text(),
            base, flash_base,
            (IMPORTS / vendor_slice.name).read_bytes(),
            (IMPORTS / installed_slice.name).read_bytes())
    return installed, reports


def totals(report):
    body = sum(match.differing_bytes or 0 for match in report.matches)
    data = sum(region.length for region in report.data_regions)
    return body, data, body + data


def load_map_markdown(extraction):
    payload = ex.to_dict(extraction)
    lines = [
        "# Installed 1.59 record, load and scatter map",
        "",
        "Generated by `tool/report_phase3.py` from",
        "`tool/extract_installed_records.py`. Offline and read-only; no device was",
        "accessed and no dump was modified. Every address is a logical flash offset",
        "or a runtime RAM address, never a raw file index.",
        "",
        "Nothing here is taken from the vendor image. Record addresses and lengths",
        "come from the installed SN_FWIN table, and the runtime layout comes from",
        "Candidate A's own scatter-region table, which the tool locates by structure",
        "and then cross-checks against the record it loads, region contiguity, and",
        "the entry image's initial stack pointer.",
        "",
        "## Result",
        "",
        "| | |",
        "|---|---|",
        f"| entry pointer | `0x{payload['entry']['pointer']:08x}` (SN_FWIN record slot 0) |",
        f"| entry initial SP | `0x{payload['entry']['initial_sp']:08x}` |",
        f"| entry reset vector | `0x{payload['entry']['reset_vector']:08x}` |",
        f"| region table | flash `0x{payload['region_table']:x}`, found by structure |",
        f"| regions | {len(payload['regions'])} |",
        f"| slices extracted | {len(payload['slices'])} |",
        f"| checks | {len(payload['checks'])}, all passing |",
        "",
        "The last region's RAM end equals the entry image's initial stack pointer",
        "exactly, in both releases. That is an independent confirmation of the whole",
        "scatter chain: the loader's idea of the top of RAM agrees with the vector",
        "table's.",
        "",
        "## Scatter regions",
        "",
        "| region | flash source | runtime destination | size | handler |",
        "|---|---|---|---|---|",
    ]
    for region in payload["regions"]:
        lines.append(
            f"| {region['index']} | `0x{region['src_flash']:x}` "
            f"(`0x{region['src']:08x}`) | `0x{region['dst']:08x}.."
            f"0x{region['dst_end']:08x}` | `0x{region['size']:x}` | "
            f"`0x{region['handler']:x}` `{region['handler_name']}` |")
    lines += [
        "",
        "Region 1's `size` is its *output* length. Its input length is not in the",
        "table; the tool takes it as running to where region 2's source begins and",
        "then proves the choice by checking that the flash-backed inputs tile record",
        "slot 1 exactly.",
        "",
        "## What is and is not materialized",
        "",
    ]
    for item in payload["runtime"]:
        if item["materialized"] and item["source_lo"] is not None:
            note = ("bytes available from flash "
                    f"`0x{item['source_lo']:x}..0x{item['source_hi']:x}`")
        elif item["materialized"]:
            note = "zero-filled, no flash source"
        else:
            note = "**contents not reconstructed** — located and sized only"
        lines.append(
            f"- `0x{item['lo']:08x}..0x{item['hi']:08x}` "
            f"(`0x{item['length']:x}`) {item['kind']}: {note}")
    lines += ["", "## Extracted slices", ""]
    for item in payload["slices"]:
        base = ("none" if item["import_base"] is None
                else f"`0x{item['import_base']:08x}`")
        lines += [
            f"### `{item['name']}`",
            "",
            f"- slot {item['slot']}, {item['role']}",
            f"- source flash `0x{item['source_lo']:x}..0x{item['source_hi']:x}` "
            f"(`0x{item['length']:x}` bytes)",
            f"- SHA-256 `{item['sha256']}`",
            f"- import base {base}",
            f"- basis: {item['import_base_basis']}",
            "",
        ]
    lines += [
        "Slices live under the ignored `ghidra/imports/` area, never in `dumps/`.",
        "Each one is proved to round-trip against the source range named above, and",
        "every byte of every active record is covered by some slice.",
        "",
        "## Source coverage",
        "",
        "Every byte of the installed dump is accounted for, with no gaps and no",
        "overlap.",
        "",
        "| range | size | fill | claimed by |",
        "|---|---|---|---|",
    ]
    for run in payload["coverage"]:
        lines.append(
            f"| `0x{run['lo']:x}..0x{run['hi']:x}` | `0x{run['length']:x}` | "
            f"{run['fill']} | {run['role']} |")
    lines += ["", "## Raw tool output", "", "```text"]
    lines += ex.report_lines(extraction)
    lines += ["```", ""]
    return "\n".join(lines)


def mapping_rows(report):
    rows = []
    for match in sorted(report.matches,
                        key=lambda item: ((item.vendor or item.installed).entry,
                                          item.vendor is None)):
        vendor = ("—" if match.vendor is None
                  else f"`0x{match.vendor.entry:08x}`")
        installed = ("—" if match.installed is None
                     else f"`0x{match.installed.entry:08x}`")
        size = (match.installed or match.vendor).size
        ranges = len((match.installed or match.vendor).ranges)
        differing = ("n/a" if match.differing_bytes is None
                     else str(match.differing_bytes))
        rows.append(
            f"| {vendor} | {installed} | {match.confidence} | "
            f"{'yes' if match.moved else 'no'} | "
            f"{'yes' if match.changed else 'no'} | `0x{size:x}` | {ranges} | "
            f"{differing} |")
    return rows


def correspondence_markdown(reports):
    report_a, report_b = reports["a"], reports["b"]
    body_a, data_a, total_a = totals(report_a)
    body_b, data_b, total_b = totals(report_b)
    gap = report_b.unaligned_gaps[0]
    lines = [
        "# Vendor 1.00.58 to installed 1.59 function correspondence",
        "",
        "Generated by `tool/report_phase3.py` from",
        "`ghidra/scripts/FalchionFunctionInventory.java` and",
        "`tool/match_functions.py`. Offline and read-only; no device was accessed,",
        "no dump was modified, and the existing Ghidra project was not touched. The",
        "slices were imported into a new ignored project, `ghidra/project-step6/`.",
        "",
        "Functions are paired on body bytes, instruction shape with scalars and",
        "addresses masked, constants, strings, size, instruction and block counts,",
        "and call degree. An address is never the *sole* signal: the identical and",
        "structural tiers use no address at all, and the one tentative rule that",
        "uses the measured shift also requires body-byte equality and can never",
        "promote a pairing above tentative.",
        "",
        "Ghidra function bodies are not necessarily contiguous, and many here are",
        "not, so every byte-level figure below comes from the real ordered body",
        "ranges rather than `entry..entry+size`.",
        "",
        "## Headline",
        "",
        "| program | vendor | installed | identical | structural | tentative | "
        "unmatched | discontiguous bodies | shift |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for tag, label in (("a", "Candidate A"), ("b", "Candidate B")):
        report = reports[tag]
        counts = mf.tally(report)
        lines.append(
            f"| {label} | {report.vendor_count} | {report.installed_count} | "
            f"{counts.get('identical', 0)} | {counts.get('structural', 0)} | "
            f"{counts.get('tentative', 0)} | {counts.get('unmatched', 0)} | "
            f"{report.discontiguous[0]}/{report.discontiguous[1]} | "
            f"`0x{report.dominant_shift:x}` |")
    lines += [
        "",
        "Both programs have the same function count in both releases and nothing",
        "is left unmatched.",
        "",
        "## The change is far smaller than the raw byte diff suggests",
        "",
        "Log 96 measured raw byte-position differences. Once functions are paired",
        "and the spans no body covers are compared in address order, the real",
        "change is:",
        "",
        "| program | function-body bytes | data-span bytes | aligned total | "
        "raw total (log 96) |",
        "|---|---|---|---|---|",
        f"| Candidate A | {body_a} | {data_a} | **{total_a}** | "
        f"{RAW_DIFFERING_BYTES['a']:,} |",
        f"| Candidate B | {body_b} | {data_b} | **{total_b}** | "
        f"{RAW_DIFFERING_BYTES['b']:,} |",
        "",
        "Candidate A did not move, so its aligned total matches log 96 exactly, and",
        "every one of those bytes turns out to be data rather than instructions.",
        "Candidate B is shifted by `0x2c` after one insertion point, so almost all",
        "of its raw differing bytes are the relocation, not a change in content.",
        "",
        "## The insertion site",
        "",
        "Exactly one paired span in Candidate B has different lengths on the two",
        "sides:",
        "",
        f"- vendor `0x{gap.vendor_lo:08x}..0x{gap.vendor_hi:08x}` "
        f"(`0x{gap.vendor_length:x}` bytes)",
        f"- installed `0x{gap.installed_lo:08x}..0x{gap.installed_hi:08x}` "
        f"(`0x{gap.installed_length:x}` bytes)",
        f"- difference: **+{gap.installed_length - gap.vendor_length} bytes**",
        "",
        "That is the whole of record slot 1's growth, and it lands in a span that no",
        "function body covers. The tool reports the span as unaligned and does not",
        "compare its bytes, because comparing across an insertion boundary would",
        "manufacture differences.",
        "",
        "No claim is made here about *what* those 44 bytes are.",
        "",
        "## Complete mapping",
        "",
        "Every pairing, in vendor-address order. `changed` means the two bodies",
        "differ in bytes, or that one side has no counterpart. `ranges` is the",
        "number of address ranges in the body, so anything above 1 is a",
        "discontiguous body.",
        "",
    ]
    for tag, label in (("a", "Candidate A"), ("b", "Candidate B")):
        report = reports[tag]
        lines += [
            f"### {label} — {len(report.matches)} pairings",
            "",
            "| vendor | installed | confidence | moved | changed | size | ranges | "
            "differing bytes |",
            "|---|---|---|---|---|---|---|---|",
        ]
        lines += mapping_rows(report)
        lines.append("")

    lines += [
        "## Addresses that must no longer be assumed equal",
        "",
        "Every relocated pairing, every tentative pairing, and every function",
        "without a counterpart.",
        "",
    ]
    for tag, label in (("a", "Candidate A"), ("b", "Candidate B")):
        report = reports[tag]
        entries = mf.must_not_assume_equal(report)
        lines += [
            f"### {label} — {len(entries)} entries",
            "",
            "| vendor | installed | reason |",
            "|---|---|---|",
        ]
        for vendor, installed, reason in entries:
            target = "absent" if installed is None else f"`0x{installed:08x}`"
            lines.append(f"| `0x{vendor:08x}` | {target} | {reason} |")
        lines.append("")

    lines += ["## Changed functions, ranked for review", ""]
    for tag, label in (("a", "Candidate A"), ("b", "Candidate B")):
        report = reports[tag]
        ranked = mf.review_ranking(report)
        lines += [f"### {label} — {len(ranked)} changed", ""]
        if not ranked:
            lines += ["Nothing changed: every body is byte-identical.", ""]
            continue
        lines += ["| vendor | installed | confidence | size | differing bytes |",
                  "|---|---|---|---|---|"]
        for match in ranked:
            vendor = ("—" if match.vendor is None
                      else f"`0x{match.vendor.entry:08x}`")
            installed = ("—" if match.installed is None
                         else f"`0x{match.installed.entry:08x}`")
            size = (match.installed or match.vendor).size
            differing = ("n/a" if match.differing_bytes is None
                         else str(match.differing_bytes))
            lines.append(f"| {vendor} | {installed} | {match.confidence} | "
                         f"`0x{size:x}` | {differing} |")
        lines.append("")

    lines += ["## Raw tool output", ""]
    for tag, label in (("a", "Candidate A"), ("b", "Candidate B")):
        lines += [f"### {label}", "", "```text"]
        lines += [line for line in mf.report_lines(reports[tag], top=0)
                  if not line.startswith("DATA ")]
        lines += ["```", "",
                  "The individual data spans are omitted from this block for "
                  "length; the complete list is in "
                  f"`vendor-to-installed-functions-app-{tag}.json`.", ""]
    return "\n".join(lines)


ARTIFACTS = ("installed-record-load-map.md", "installed-record-load-map.json",
             "vendor-to-installed-functions.md",
             "vendor-to-installed-functions-app-a.json",
             "vendor-to-installed-functions-app-b.json")


def render():
    extraction, reports = load_reports()
    return {
        "installed-record-load-map.md": load_map_markdown(extraction),
        "installed-record-load-map.json": json.dumps(
            ex.to_dict(extraction), indent=2, sort_keys=True) + "\n",
        "vendor-to-installed-functions.md": correspondence_markdown(reports),
        "vendor-to-installed-functions-app-a.json": json.dumps(
            mf.to_dict(reports["a"]), indent=2, sort_keys=True) + "\n",
        "vendor-to-installed-functions-app-b.json": json.dumps(
            mf.to_dict(reports["b"]), indent=2, sort_keys=True) + "\n",
    }


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the artifacts on disk match a fresh render")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    try:
        rendered = render()
    except (OSError, fi.ImageFormatError, ex.ExtractError, ValueError) as exc:
        print(f"RESULT reports_written=0 error={exc}")
        return 1
    stale = []
    for name, text in rendered.items():
        path = NOTES / name
        if args.check:
            current = path.read_text() if path.exists() else None
            if current != text:
                stale.append(name)
            continue
        path.write_text(text)
        print(f"WROTE notes/{name} ({len(text)} bytes)")
    if args.check:
        for name in ARTIFACTS:
            print(f"  {'STALE' if name in stale else 'CURRENT'} notes/{name}")
        print(f"RESULT reports_current={not stale} stale={len(stale)}")
        return 1 if stale else 0
    print(f"RESULT reports_written={len(rendered)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
